modLoader="lowcodefml"
loaderVersion="[59,)"
license="MIT"

[[mods]]
modId="better_craftables"
version="6.3.0-beta"
displayName="Better Craftables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/better-craftables"
credits="https://github.com/Classics-Craftworks/Better-Craftables/wiki/Credits"
authors="Classic36"
description="Adds some quality-of-life crafting and smelting recipes to the game."

[[dependencies.better_craftables]]
    modId="forge"
    mandatory=true
    versionRange="[59,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.better_craftables]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.9,26.1]"
    ordering="AFTER"
    side="BOTH"