modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="better_craftables"
version="6.3.0"
displayName="Better Craftables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/better-craftables"
credits="https://github.com/Classics-Craftworks/Better-Craftables/wiki/Credits"
authors="Classic36"
description="Adds some quality-of-life crafting and smelting recipes to the game."

[[dependencies.better_craftables]]
    modId="neoforge"
    type="required"
    versionRange="[21.9.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.better_craftables]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.9,1.21.11]"
    ordering="AFTER"
    side="BOTH"