modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="better_craftables"
version="7.0.0-alpha"
displayName="Better Craftables"
logoFile="pack.png"
displayURL="https://modrinth.com/datapack/better-craftables"
credits="https://github.com/Classics-Craftworks/Better-Craftables/wiki/Credits"
authors="Classic36"
description="Adds some quality-of-life crafting and smelting recipes to the game."

[[dependencies.better_craftables]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.0.0-alpha.5+snapshot-2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.better_craftables]]
    modId="minecraft"
    type="required"
    versionRange="[26.1-snapshot-2,)"
    ordering="AFTER"
    side="BOTH"